package gui;

import dao.DistritoDAO;
import dao.EmpleadoDAO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import to.DistritoTO;
import to.EmpleadoTO;

public class EmpleadoGUI extends javax.swing.JInternalFrame {

    DefaultTableModel objDtm;
    ResultSet rsEmpleado;
    ResultSet rsDistrito;
    EmpleadoDAO objEmpleadoDAO = new EmpleadoDAO();
    DistritoDAO objDistritoDAO = new DistritoDAO();

    String ruta;

    int xidDistrito;
    boolean sw;
    ButtonGroup objButtonGroup = new ButtonGroup();

    public EmpleadoGUI() {
        initComponents();
        setSize(752, 517);
        objButtonGroup.add(jrbtFemenino);
        objButtonGroup.add(jrbtMasculino);
        setVisible(true);
        objDtm = (DefaultTableModel) jtblRegistros.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtBuscar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jtxtObservacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtApPaterno = new javax.swing.JTextField();
        jrbtFemenino = new javax.swing.JRadioButton();
        jrbtMasculino = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jtxtApMaterno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtTelefono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtCelular = new javax.swing.JTextField();
        jlblFoto = new javax.swing.JLabel();
        jcmbDistrito = new javax.swing.JComboBox<>();
        jbtnSeleccionar = new javax.swing.JButton();
        jtxtRuta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtnNuevo = new javax.swing.JButton();
        jbtnGrabar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnBorrar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblRegistros = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("INGRESE EL APELLIDO PATERNO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 11, -1, -1));

        jtxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBuscarActionPerformed(evt);
            }
        });
        jtxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 6, 248, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CODIGO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jtxtCodigo.setEditable(false);
        jPanel1.add(jtxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 150, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("E-MAIL:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jtxtEmail.setEditable(false);
        jPanel1.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 150, -1));

        jtxtObservacion.setEditable(false);
        jPanel1.add(jtxtObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 150, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("OBSERVACION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("NOMBRE:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jtxtNombre.setEditable(false);
        jPanel1.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 150, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("SEXO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("AP. PATERNO:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jtxtApPaterno.setEditable(false);
        jPanel1.add(jtxtApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 150, -1));

        jrbtFemenino.setForeground(new java.awt.Color(0, 0, 0));
        jrbtFemenino.setText("FEMENINO");
        jrbtFemenino.setEnabled(false);
        jPanel1.add(jrbtFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 105, -1, -1));

        jrbtMasculino.setForeground(new java.awt.Color(0, 0, 0));
        jrbtMasculino.setText("MASCULINO");
        jrbtMasculino.setEnabled(false);
        jPanel1.add(jrbtMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 105, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("AP. MATERNO:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jtxtApMaterno.setEditable(false);
        jPanel1.add(jtxtApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 150, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("DIRECCION:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jtxtDireccion.setEditable(false);
        jPanel1.add(jtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 150, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("DISTRITO:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("TELF. FIJO:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jtxtTelefono.setEditable(false);
        jPanel1.add(jtxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 150, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("CELULAR:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jtxtCelular.setEditable(false);
        jPanel1.add(jtxtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 150, -1));

        jlblFoto.setForeground(new java.awt.Color(0, 0, 0));
        jlblFoto.setText("FOTO");
        jlblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jlblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 140, 140));

        jcmbDistrito.setEnabled(false);
        jcmbDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbDistritoActionPerformed(evt);
            }
        });
        jPanel1.add(jcmbDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 150, -1));

        jbtnSeleccionar.setText("Seleccionar");
        jbtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        jtxtRuta.setEditable(false);
        jPanel1.add(jtxtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 550, 350));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(6, 1, 10, 15));

        jbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo.png"))); // NOI18N
        jbtnNuevo.setText("Nuevo");
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnNuevo);

        jbtnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/grabar.png"))); // NOI18N
        jbtnGrabar.setText("Grabar");
        jbtnGrabar.setEnabled(false);
        jbtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGrabarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnGrabar);

        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setEnabled(false);
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCancelar);

        jbtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        jbtnEditar.setText("Editar");
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnEditar);

        jbtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar.png"))); // NOI18N
        jbtnBorrar.setText("Borrar");
        jbtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBorrar);

        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir.png"))); // NOI18N
        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSalir);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 140, 350));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "AP. PATERNO", "AP. MATERNO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblRegistrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblRegistros);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 80));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 700, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBuscarActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        if (jtxtCodigo.getText().isEmpty()) {
            return;
        }
        reproducirSonido("actualizar");
        habilitarControles(true);
        sw = false;
        llenarCombo();
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        sw = true;
        reproducirSonido("nuevo");
        habilitarControles(true);
        limpiarControles();
        llenarCombo();
    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        habilitarControles(false);
        limpiarControles();
        jtxtBuscar.grabFocus();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jtxtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarKeyReleased
        try {
            limpiarJTable();
            String nombre = jtxtBuscar.getText().strip();
            if (!nombre.isEmpty()) {
                rsEmpleado = objEmpleadoDAO.search(nombre);
                while (rsEmpleado.next()) {
                    Object[] registro = {
                        rsEmpleado.getInt(1),
                        rsEmpleado.getString(2),
                        rsEmpleado.getString(3),
                        rsEmpleado.getString(4),};
                    objDtm.addRow(registro);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage() + " " + jtxtBuscar.getText());
        }
    }//GEN-LAST:event_jtxtBuscarKeyReleased

    private void jbtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGrabarActionPerformed
        try {
            String mensaje = "";

            String rutaMasculino = "C:\\fotosDemo\\masculino.jpg";
            String rutaFemenino = "C:\\fotosDemo\\femenino.png";

            EmpleadoTO objEmpleadoTO = new EmpleadoTO();
            objEmpleadoTO.setNombEmpl(jtxtNombre.getText().strip());
            objEmpleadoTO.setApatEmpl(jtxtApPaterno.getText().strip());
            objEmpleadoTO.setAmatEmpl(jtxtApMaterno.getText().strip());
            if (jrbtMasculino.isSelected()) {
                objEmpleadoTO.setSexoEmpl("M");
            } else {
                objEmpleadoTO.setSexoEmpl("F");
            }
            objEmpleadoTO.setDireEmpl(jtxtDireccion.getText().strip());
            obtenerIdDistrito();
            objEmpleadoTO.setIdDistrito(xidDistrito);
            objEmpleadoTO.setTelfEmpl(jtxtTelefono.getText().strip());
            objEmpleadoTO.setCeluEmpl(jtxtCelular.getText().strip());
            objEmpleadoTO.setEmailEmpl(jtxtEmail.getText().strip());
            objEmpleadoTO.setObsEmpl(jtxtObservacion.getText().strip());

            if (jtxtRuta.getText().isEmpty()) {
                if (jrbtMasculino.isSelected()) {
                    objEmpleadoTO.setFotoEmpl(rutaMasculino);
                }
                if (jrbtFemenino.isSelected()) {
                    objEmpleadoTO.setFotoEmpl(rutaFemenino);
                }
            } else {
                objEmpleadoTO.setFotoEmpl(jtxtRuta.getText());
            }

            if (sw) {
                objEmpleadoDAO.insert(objEmpleadoTO);
                mensaje = "Registro guardado";
            } else {
                objEmpleadoTO.setIdEmpleado(Integer.parseInt(jtxtCodigo.getText().strip()));
                objEmpleadoDAO.update(objEmpleadoTO);
                mensaje = "Registro actualizado";
            }
            reproducirSonido("guardado");
            habilitarControles(false);
            JOptionPane.showMessageDialog(rootPane, mensaje);
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Grabar:" + e.getMessage());
        }
    }//GEN-LAST:event_jbtnGrabarActionPerformed

    private void jbtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBorrarActionPerformed
        String codigo = jtxtCodigo.getText();
        if (codigo.isEmpty()) {
            return;
        }
        
        try {
            int opcion = JOptionPane.showConfirmDialog(rootPane, "Eliminar el registro?", "Eliminar", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                EmpleadoTO empleadoTO = new EmpleadoTO();
                empleadoTO.setIdEmpleado(Integer.parseInt(codigo));
                objEmpleadoDAO.delete(empleadoTO);
                limpiarControles();
                reproducirSonido("eliminado");
                JOptionPane.showMessageDialog(rootPane, "Registro borrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jbtnBorrarActionPerformed

    private void jcmbDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbDistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbDistritoActionPerformed

    private void jtblRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblRegistrosMouseClicked

        try {
            int id = (int) objDtm.getValueAt(jtblRegistros.getSelectedRow(), 0);

            try ( // Llamar a tu método DAO
                    ResultSet rsEmpl = objEmpleadoDAO.searchID(id)) {
                if (rsEmpl.next()) {
                    jtxtCodigo.setText(String.valueOf(rsEmpl.getInt(1)));
                    jtxtNombre.setText(rsEmpl.getString(2));
                    jtxtApPaterno.setText(rsEmpl.getString(3));
                    jtxtApMaterno.setText(rsEmpl.getString(4));

                    String sexo = rsEmpl.getString(5);
                    jrbtMasculino.setSelected("M".equalsIgnoreCase(sexo));
                    jrbtFemenino.setSelected("F".equalsIgnoreCase(sexo));

                    jtxtDireccion.setText(rsEmpl.getString(6));

                    jcmbDistrito.removeAllItems();
                    jcmbDistrito.addItem(rsEmpl.getString(7));

                    jtxtTelefono.setText(rsEmpl.getString(8));
                    jtxtCelular.setText(rsEmpl.getString(9));
                    jtxtEmail.setText(rsEmpl.getString(10));
                    jtxtObservacion.setText(rsEmpl.getString(11));

                    // --- Carga segura de la imagen ---
                    Blob fotoBlob = rsEmpl.getBlob(12);
                    if (fotoBlob != null && fotoBlob.length() > 0) {
                        System.out.println("Imgena existe");
                        byte[] data = fotoBlob.getBytes(1, (int) fotoBlob.length());
                        BufferedImage foto = ImageIO.read(new ByteArrayInputStream(data));

                        if (foto != null) {
                            System.out.println("Imagen contruida");
                            ImageIcon imagen = new ImageIcon(foto);
                            Icon icon = new ImageIcon(imagen.getImage().getScaledInstance(
                                    jlblFoto.getWidth(),
                                    jlblFoto.getHeight(),
                                    Image.SCALE_SMOOTH
                            ));
                            jlblFoto.setIcon(icon);
                        } else {
                            jlblFoto.setIcon(null);
                        }
                    } else {
                        jlblFoto.setIcon(null);
                        System.out.println("⚠️ No hay imagen almacenada para este registro.");
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al cargar empleado: " + e.getMessage());
        }


    }//GEN-LAST:event_jtblRegistrosMouseClicked

    private void jbtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSeleccionarActionPerformed
        JFileChooser objJFileChooser = new JFileChooser();
        int op = objJFileChooser.showOpenDialog(this);
        
        if (op == objJFileChooser.APPROVE_OPTION) {
            ruta = objJFileChooser.getSelectedFile().getAbsolutePath();
            jlblFoto.setIcon(new ImageIcon(ruta));

            // Escalar la imagen al tamaño del JLabel
            ImageIcon iconoOriginal = new ImageIcon(ruta);
            Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                    jlblFoto.getWidth(),
                    jlblFoto.getHeight(),
                    Image.SCALE_SMOOTH
            );
            jlblFoto.setIcon(new ImageIcon(imagenEscalada));
            jtxtRuta.setText(ruta);
        }
    }//GEN-LAST:event_jbtnSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnBorrar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnGrabar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JButton jbtnSeleccionar;
    private javax.swing.JComboBox<String> jcmbDistrito;
    private javax.swing.JLabel jlblFoto;
    private javax.swing.JRadioButton jrbtFemenino;
    private javax.swing.JRadioButton jrbtMasculino;
    private javax.swing.JTable jtblRegistros;
    private javax.swing.JTextField jtxtApMaterno;
    private javax.swing.JTextField jtxtApPaterno;
    private javax.swing.JTextField jtxtBuscar;
    private javax.swing.JTextField jtxtCelular;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtObservacion;
    private javax.swing.JTextField jtxtRuta;
    private javax.swing.JTextField jtxtTelefono;
    // End of variables declaration//GEN-END:variables

    private void limpiarJTable() {
        objDtm.setRowCount(0);
    }

    private void habilitarControles(boolean b) {
        JTextField[] arrayJTextFields = {
            jtxtApMaterno,
            jtxtApPaterno,
            jtxtCelular,
            jtxtDireccion,
            jtxtEmail,
            jtxtNombre,
            jtxtObservacion,
            jtxtTelefono};

        for (JTextField obj : arrayJTextFields) {
            obj.setEditable(b);
        }
        jrbtFemenino.setEnabled(b);
        jrbtMasculino.setEnabled(b);
        jcmbDistrito.setEnabled(b);

        jbtnGrabar.setEnabled(b);
        jbtnCancelar.setEnabled(b);
        jbtnNuevo.setEnabled(!b);
        jbtnEditar.setEnabled(!b);
        jbtnBorrar.setEnabled(!b);
        jbtnSalir.setEnabled(!b);

        jtxtBuscar.setEditable(!b);
        jtxtNombre.grabFocus();
    }

    private void limpiarControles() {
        limpiarJTable();
        JTextField[] arrayJTextFields = {
            jtxtApMaterno,
            jtxtApPaterno,
            jtxtBuscar,
            jtxtCelular,
            jtxtCodigo,
            jtxtDireccion,
            jtxtEmail,
            jtxtNombre,
            jtxtObservacion,
            jtxtTelefono, jtxtRuta};

        for (JTextField obj : arrayJTextFields) {
            obj.setText("");
        }
        jlblFoto.setIcon(null);
        jcmbDistrito.removeAllItems();
        objButtonGroup.clearSelection();
    }

    private void llenarCombo() {
        try {
            rsDistrito = objDistritoDAO.search("%");
            if (sw) {
                while (rsDistrito.next()) {
                    jcmbDistrito.addItem(rsDistrito.getString(2));
                }
            } else {
                String nombre = jcmbDistrito.getSelectedItem().toString();
                while (rsDistrito.next()) {
                    if (!nombre.equals(rsDistrito.getString(2))) {
                        jcmbDistrito.addItem(rsDistrito.getString(2));
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo acceder a los distritos");
        }
    }

    private void obtenerIdDistrito() {
        try {
            rsDistrito.first();
            String nombre = jcmbDistrito.getSelectedItem().toString();

            do {
                if (nombre.equals(rsDistrito.getString(2))) {
                    xidDistrito = rsDistrito.getInt(1);
                    rsDistrito.last();
                }
            } while (rsDistrito.next());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void reproducirSonido(String nombre) {
        try {
            String ruta = "src/sonidos/" + nombre + ".wav"; // Carpeta donde guardas tus audios
            File archivo = new File(ruta);
            if (!archivo.exists()) {
                System.err.println("No se encontró el archivo: " + ruta);
                return;
            }
            AudioInputStream audio = AudioSystem.getAudioInputStream(archivo);
            Clip clip = AudioSystem.getClip();
            clip.open(audio);
            clip.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
