/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import java.awt.Component;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chila
 */
public class FacturaGUI extends javax.swing.JInternalFrame {

    boolean sw;
    DefaultTableModel dtm;
    double precio;
    int cantidad;
    double importe;
    double subtotal;
    double igv;
    double total;

    /**
     * Creates new form FacturaGUI
     */
    public FacturaGUI() {
        initComponents();
        this.dtm = (DefaultTableModel) tblRegistros.getModel();

        this.setSize(672, 682);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCliente = new javax.swing.JButton();
        txtDirecClie = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtNombClie = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaterno = new javax.swing.JTextField();
        txtIdEmpleado = new javax.swing.JTextField();
        txtNombEmpl = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        btnEmpleado = new javax.swing.JButton();
        pnlProducto = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtImporte = new javax.swing.JTextField();
        txtIdProducto = new javax.swing.JTextField();
        txtNombProd = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtSubTotal = new javax.swing.JTextField();
        txtIgv = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtFactura = new javax.swing.JTextField();

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Celular:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 85, -1, 20));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Codigo cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre cliente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, 20));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Direccion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ciudad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 85, -1, 20));

        btnCliente.setText("...");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, 25));

        txtDirecClie.setEditable(false);
        jPanel1.add(txtDirecClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 60, 485, -1));

        txtCelular.setEditable(false);
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 85, 140, -1));

        txtNombClie.setEditable(false);
        jPanel1.add(txtNombClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 35, 485, -1));

        txtCiudad.setEditable(false);
        jPanel1.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 85, 170, -1));

        txtIdCliente.setEditable(false);
        jPanel1.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 10, 170, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 620, 115));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ap. Materno:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 20));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Codigo empleado:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Ap. Paterno:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, 20));

        txtMaterno.setEditable(false);
        jPanel2.add(txtMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 110, -1));

        txtIdEmpleado.setEditable(false);
        jPanel2.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 10, 110, -1));

        txtNombEmpl.setEditable(false);
        jPanel2.add(txtNombEmpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 40, 110, -1));

        txtPaterno.setEditable(false);
        jPanel2.add(txtPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 100, -1));

        btnEmpleado.setText("...");
        jPanel2.add(btnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 40, 25));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 620, 75));

        pnlProducto.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Importe:");
        pnlProducto.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 35, -1, 22));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("ID producto:");
        pnlProducto.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nombre:");
        pnlProducto.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, 20));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Cantidad:");
        pnlProducto.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 35, -1, 22));

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        pnlProducto.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.setEnabled(false);
        pnlProducto.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        txtImporte.setEditable(false);
        pnlProducto.add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 35, 120, -1));

        txtIdProducto.setEditable(false);
        pnlProducto.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 165, -1));

        txtNombProd.setEditable(false);
        pnlProducto.add(txtNombProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 35, 130, -1));

        txtCantidad.setEditable(false);
        pnlProducto.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 35, 100, -1));

        btnProducto.setText("...");
        pnlProducto.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, 25));

        jPanel4.add(pnlProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 620, 100));

        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "PRECIO", "CANTIDAD", "IMPORTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRegistros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblRegistros);
        if (tblRegistros.getColumnModel().getColumnCount() > 0) {
            tblRegistros.getColumnModel().getColumn(0).setResizable(false);
            tblRegistros.getColumnModel().getColumn(1).setResizable(false);
            tblRegistros.getColumnModel().getColumn(2).setResizable(false);
            tblRegistros.getColumnModel().getColumn(3).setResizable(false);
            tblRegistros.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 620, 150));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("STORE S.A.");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel16.setText("Factura:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 7, -1, 20));

        jLabel17.setText("Fecha:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 32, -1, 20));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jPanel5.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 40));

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/grabar.png"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.setEnabled(false);
        btnGrabar.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jPanel5.add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 40));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jPanel5.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 55, 140, 40));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setMargin(new java.awt.Insets(10, 10, 10, 10));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel5.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 55, 140, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 330, 100));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Total:");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("IGV 18%:");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Sub Total:");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        txtTotal.setEditable(false);
        jPanel6.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, 25));

        txtSubTotal.setEditable(false);
        jPanel6.add(txtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 120, 25));

        txtIgv.setEditable(false);
        jPanel6.add(txtIgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 120, 25));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 220, 100));
        jPanel4.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 32, 130, -1));
        jPanel4.add(txtFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 7, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        BuscarClienteGUI buscarClienteGUI = new BuscarClienteGUI();
    }//GEN-LAST:event_btnClienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlProducto;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDirecClie;
    private javax.swing.JTextField txtFactura;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtIgv;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombClie;
    private javax.swing.JTextField txtNombEmpl;
    private javax.swing.JTextField txtNombProd;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void habilitarControles(boolean b) {
        txtCantidad.setEditable(b);
        btnGrabar.setEnabled(b);
        btnCancelar.setEnabled(b);
        btnCliente.setEnabled(b);
        btnEmpleado.setEnabled(b);
        btnProducto.setEnabled(b);
        btnAgregar.setEnabled(b);
        btnEliminar.setEnabled(b);
        btnNuevo.setEnabled(!b);
        btnSalir.setEnabled(!b);
    }

    private void limpiarControles() {
        JTextField[] textFields = {
            txtCantidad, txtCelular, txtCiudad, txtDirecClie,
            txtIdCliente, txtIdEmpleado, txtIdProducto, txtImporte,
            txtMaterno, txtNombClie, txtNombEmpl, txtNombProd,
            txtPaterno, txtFactura, txtFecha, txtIgv,
            txtSubTotal, txtTotal
        };

        for (JTextField textField : textFields) {
            textField.setText("");
        }
        limpiarJTable();
    }

    private void limpiarJTable() {
        dtm.setRowCount(0);
    }

    private void limpiarProducto() {
        txtIdProducto.setText("");
        txtNombProd.setText("");
        txtCantidad.setText("");
        txtImporte.setText("");
        cantidad = 0;
        precio = 0;
        importe = 0;
    }

}
