package gui;

public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuMante = new javax.swing.JMenu();
        manCliente = new javax.swing.JMenuItem();
        manDistrito = new javax.swing.JMenuItem();
        manEmpleado = new javax.swing.JMenuItem();
        manProducto = new javax.swing.JMenuItem();
        manSalir = new javax.swing.JMenuItem();
        mnuFacturacion = new javax.swing.JMenu();
        facGenerar = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        repCliente = new javax.swing.JMenuItem();
        repDistrito = new javax.swing.JMenuItem();
        repFactura = new javax.swing.JMenuItem();
        repProducto = new javax.swing.JMenuItem();
        mnuSeguridad = new javax.swing.JMenu();
        segAuditoria = new javax.swing.JMenuItem();
        segBackup = new javax.swing.JMenuItem();
        segRestore = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        ayuAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuMante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/maintenance.png"))); // NOI18N
        mnuMante.setMnemonic('f');
        mnuMante.setText("Mantenimiento");
        mnuMante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManteActionPerformed(evt);
            }
        });

        manCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cliente.png"))); // NOI18N
        manCliente.setMnemonic('o');
        manCliente.setText("Cliente");
        manCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manClienteActionPerformed(evt);
            }
        });
        mnuMante.add(manCliente);

        manDistrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/distrito.png"))); // NOI18N
        manDistrito.setMnemonic('s');
        manDistrito.setText("Distrito");
        manDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manDistritoActionPerformed(evt);
            }
        });
        mnuMante.add(manDistrito);

        manEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/empleado.png"))); // NOI18N
        manEmpleado.setText("Empleado");
        manEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manEmpleadoActionPerformed(evt);
            }
        });
        mnuMante.add(manEmpleado);

        manProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/producto.png"))); // NOI18N
        manProducto.setMnemonic('a');
        manProducto.setText("Producto");
        manProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manProductoActionPerformed(evt);
            }
        });
        mnuMante.add(manProducto);

        manSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir.png"))); // NOI18N
        manSalir.setMnemonic('x');
        manSalir.setText("Salir");
        manSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manSalirActionPerformed(evt);
            }
        });
        mnuMante.add(manSalir);

        menuBar.add(mnuMante);

        mnuFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/factura_color.png"))); // NOI18N
        mnuFacturacion.setMnemonic('e');
        mnuFacturacion.setText("Facturación");

        facGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/factura_1.png"))); // NOI18N
        facGenerar.setMnemonic('t');
        facGenerar.setText("Generar factura");
        facGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facGenerarActionPerformed(evt);
            }
        });
        mnuFacturacion.add(facGenerar);

        menuBar.add(mnuFacturacion);

        mnuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/array.png"))); // NOI18N
        mnuReportes.setMnemonic('h');
        mnuReportes.setText("Reportes");

        repCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cliente.png"))); // NOI18N
        repCliente.setMnemonic('c');
        repCliente.setText("Cliente");
        mnuReportes.add(repCliente);

        repDistrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/distrito.png"))); // NOI18N
        repDistrito.setMnemonic('a');
        repDistrito.setText("Distrito");
        mnuReportes.add(repDistrito);

        repFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/factura_color.png"))); // NOI18N
        repFactura.setText("Factura");
        mnuReportes.add(repFactura);

        repProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/producto.png"))); // NOI18N
        repProducto.setText("Producto");
        repProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repProductoActionPerformed(evt);
            }
        });
        mnuReportes.add(repProducto);

        menuBar.add(mnuReportes);

        mnuSeguridad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/seguridad.png"))); // NOI18N
        mnuSeguridad.setText("Seguridad");

        segAuditoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/reunion.png"))); // NOI18N
        segAuditoria.setText("Auditoria");
        mnuSeguridad.add(segAuditoria);

        segBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/backup.png"))); // NOI18N
        segBackup.setText("Backup");
        mnuSeguridad.add(segBackup);

        segRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/restore.png"))); // NOI18N
        segRestore.setText("Restore");
        mnuSeguridad.add(segRestore);

        menuBar.add(mnuSeguridad);

        mnuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ayuda.png"))); // NOI18N
        mnuAyuda.setText("Ayuda");

        ayuAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/acercaDe.png"))); // NOI18N
        ayuAcerca.setText("Acerca de...");
        mnuAyuda.add(ayuAcerca);

        menuBar.add(mnuAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_manSalirActionPerformed

    private void manClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manClienteActionPerformed

    private void repProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repProductoActionPerformed

    private void manProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manProductoActionPerformed
        MenuGUI.desktopPane.add(new ProductoGUI());
    }//GEN-LAST:event_manProductoActionPerformed

    private void manDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manDistritoActionPerformed
        MenuGUI.desktopPane.add(new DistritoGUI());
    }//GEN-LAST:event_manDistritoActionPerformed

    private void mnuManteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManteActionPerformed
        MenuGUI.desktopPane.add(new EmpleadoGUI());
    }//GEN-LAST:event_mnuManteActionPerformed

    private void manEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manEmpleadoActionPerformed
        MenuGUI.desktopPane.add(new EmpleadoGUI());
    }//GEN-LAST:event_manEmpleadoActionPerformed

    private void facGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facGenerarActionPerformed
        MenuGUI.desktopPane.add(new FacturaGUI());
    }//GEN-LAST:event_facGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ayuAcerca;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem facGenerar;
    private javax.swing.JMenuItem manCliente;
    private javax.swing.JMenuItem manDistrito;
    private javax.swing.JMenuItem manEmpleado;
    private javax.swing.JMenuItem manProducto;
    private javax.swing.JMenuItem manSalir;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuFacturacion;
    private javax.swing.JMenu mnuMante;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenu mnuSeguridad;
    private javax.swing.JMenuItem repCliente;
    private javax.swing.JMenuItem repDistrito;
    private javax.swing.JMenuItem repFactura;
    private javax.swing.JMenuItem repProducto;
    private javax.swing.JMenuItem segAuditoria;
    private javax.swing.JMenuItem segBackup;
    private javax.swing.JMenuItem segRestore;
    // End of variables declaration//GEN-END:variables

}
