package gui;

import dao.ProductoDAO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import to.ProductoTO;

public class ProductoGUI extends javax.swing.JInternalFrame {

    DefaultTableModel objDtm;
    ResultSet rsProducto;
    ProductoDAO objProductoDAO = new ProductoDAO();
    int xidProducto;
    boolean sw;
    String ruta;

    public ProductoGUI() {
        initComponents();
        setSize(661, 463);
        setVisible(true);
        objDtm = (DefaultTableModel) jtblRegistros.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtblRegistros = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtCodigo = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtPrecio = new javax.swing.JTextField();
        jtxtObservacion = new javax.swing.JTextField();
        jlblFoto = new javax.swing.JLabel();
        jbtnSeleccionar = new javax.swing.JButton();
        jtxtRuta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtnNuevo = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jbtnGrabar = new javax.swing.JButton();
        jbtnBorrar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtBuscar = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(415, 473));
        getContentPane().setLayout(null);

        jtblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE"
            }
        ));
        jtblRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblRegistrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblRegistros);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 35, 610, 110);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CODIGO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(25, 15, 100, 16);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NOMBRE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(25, 45, 100, 16);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("PRECIO");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(25, 75, 100, 16);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("OBSERVACION");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(25, 105, 100, 16);

        jtxtCodigo.setEditable(false);
        jPanel1.add(jtxtCodigo);
        jtxtCodigo.setBounds(140, 10, 225, 26);

        jtxtNombre.setEditable(false);
        jPanel1.add(jtxtNombre);
        jtxtNombre.setBounds(140, 40, 225, 26);

        jtxtPrecio.setEditable(false);
        jPanel1.add(jtxtPrecio);
        jtxtPrecio.setBounds(140, 70, 225, 25);

        jtxtObservacion.setEditable(false);
        jPanel1.add(jtxtObservacion);
        jtxtObservacion.setBounds(140, 100, 225, 25);

        jlblFoto.setText("Foto");
        jlblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jlblFoto);
        jlblFoto.setBounds(390, 10, 110, 110);

        jbtnSeleccionar.setText("Imagen");
        jbtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSeleccionar);
        jbtnSeleccionar.setBounds(510, 10, 76, 26);
        jPanel1.add(jtxtRuta);
        jtxtRuta.setBounds(510, 50, 68, 26);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 161, 610, 130);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo.png"))); // NOI18N
        jbtnNuevo.setText("Nuevo");
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });

        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setEnabled(false);
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jbtnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/grabar.png"))); // NOI18N
        jbtnGrabar.setText("Grabar");
        jbtnGrabar.setEnabled(false);
        jbtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGrabarActionPerformed(evt);
            }
        });

        jbtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar.png"))); // NOI18N
        jbtnBorrar.setText("Borrar");
        jbtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBorrarActionPerformed(evt);
            }
        });

        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir.png"))); // NOI18N
        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jbtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        jbtnEditar.setText("Editar");
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(70, 300, 490, 118);

        jLabel1.setText("INGRESE EL PRODUCTO A BUSCAR:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 200, 16);

        jtxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBuscarActionPerformed(evt);
            }
        });
        jtxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtBuscar);
        jtxtBuscar.setBounds(250, 5, 260, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        habilitarControles(true);
        reproducirSonido("nuevo");
        limpiarControles();
        sw = true;
    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGrabarActionPerformed
        try {

            String rutaDefault = "C:\\fotosDemo\\demoProd.png";
            String mensaje = "";
            ProductoTO objProductoTO = new ProductoTO();
            objProductoTO.setNombProd(jtxtNombre.getText());
            objProductoTO.setPrecProd(Double.valueOf(jtxtPrecio.getText().replace(',', '.')));
            objProductoTO.setObsvProd(jtxtObservacion.getText());

            if (jtxtRuta.getText().isEmpty()) {

                objProductoTO.setFotoProd(rutaDefault);
            } else {
                objProductoTO.setFotoProd(jtxtRuta.getText().strip());
            }

            if (sw) {
                objProductoDAO.insert(objProductoTO);
                mensaje = "Registro guardado";
            } else {
                objProductoTO.setIdProducto(Integer.parseInt(jtxtCodigo.getText()));
                objProductoDAO.update(objProductoTO);
                mensaje = "Registro actualizado";
            }
            habilitarControles(false);
            reproducirSonido("guardado");
            JOptionPane.showMessageDialog(rootPane, mensaje);
            limpiarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbtnGrabarActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        if (jtxtCodigo.getText().isEmpty()) {
            return;
        }
        reproducirSonido("actualizar");
        habilitarControles(true);
        sw = false;
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jtxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBuscarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        habilitarControles(false);
        limpiarControles();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jtxtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarKeyReleased
        try {
            limpiarJTable();
            String nombre = jtxtBuscar.getText().strip();
            if (!nombre.isEmpty()) {
                rsProducto = objProductoDAO.search(nombre);
                while (rsProducto.next()) {
                    Object[] registro = {rsProducto.getInt(1), rsProducto.getString(2)};
                    objDtm.addRow(registro);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage() + " " + jtxtBuscar.getText());
        }
    }//GEN-LAST:event_jtxtBuscarKeyReleased

    private void jtblRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblRegistrosMouseClicked

        try {
            xidProducto = Integer.parseInt(jtblRegistros.getValueAt(jtblRegistros.getSelectedRow(), 0).toString());

            try ( // Llamar a tu método DAO
                    ResultSet rsProd = objProductoDAO.searchID(xidProducto)) {
                if (rsProd.next()) {
                    jtxtCodigo.setText(String.valueOf(rsProd.getInt(1)));
                    jtxtNombre.setText(rsProd.getString(2));
                    jtxtPrecio.setText(String.format("%.2f", rsProd.getDouble(3)));
                    jtxtObservacion.setText(rsProd.getString(4));

                    // --- Carga segura de la imagen ---
                    Blob fotoBlob = rsProd.getBlob(5);
                    if (fotoBlob != null && fotoBlob.length() > 0) {
                        System.out.println("Imgena existe");
                        byte[] data = fotoBlob.getBytes(1, (int) fotoBlob.length());
                        BufferedImage foto = ImageIO.read(new ByteArrayInputStream(data));

                        if (foto != null) {
                            System.out.println("Imagen contruida");
                            ImageIcon imagen = new ImageIcon(foto);
                            Icon icon = new ImageIcon(imagen.getImage().getScaledInstance(
                                    jlblFoto.getWidth(),
                                    jlblFoto.getHeight(),
                                    Image.SCALE_SMOOTH
                            ));
                            jlblFoto.setIcon(icon);
                        } else {
                            jlblFoto.setIcon(null);
                        }
                    } else {
                        jlblFoto.setIcon(null);
                        System.out.println("⚠️ No hay imagen almacenada para este registro.");
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al cargar empleado: " + e.getMessage());
        }
    }//GEN-LAST:event_jtblRegistrosMouseClicked

    private void jbtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBorrarActionPerformed
        try {
            if (jtxtCodigo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
                return;
            }

            int op = JOptionPane.showConfirmDialog(rootPane, "¿Eliminar?", "PREGUNTA", JOptionPane.YES_NO_OPTION);

            if (op != JOptionPane.YES_OPTION) {
                return;
            }

            ProductoTO objProductoTO = new ProductoTO();
            objProductoTO.setIdProducto(Integer.parseInt(jtxtCodigo.getText()));
            objProductoDAO.delete(objProductoTO);
            reproducirSonido("eliminado");
            limpiarControles();
            JOptionPane.showMessageDialog(null, "Registro eliminado");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbtnBorrarActionPerformed

    private void jbtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSeleccionarActionPerformed
        JFileChooser objJFileChooser = new JFileChooser();
        int op = objJFileChooser.showOpenDialog(this);
        if (op == objJFileChooser.APPROVE_OPTION) {
            ruta = objJFileChooser.getSelectedFile().getAbsolutePath();
            jlblFoto.setIcon(new ImageIcon(ruta));

            // Escalar la imagen al tamaño del JLabel
            ImageIcon iconoOriginal = new ImageIcon(ruta);
            Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                    jlblFoto.getWidth(),
                    jlblFoto.getHeight(),
                    Image.SCALE_SMOOTH
            );
            jlblFoto.setIcon(new ImageIcon(imagenEscalada));
            jtxtRuta.setText(ruta);
        }
    }//GEN-LAST:event_jbtnSeleccionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnBorrar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnGrabar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JButton jbtnSeleccionar;
    private javax.swing.JLabel jlblFoto;
    private javax.swing.JTable jtblRegistros;
    private javax.swing.JTextField jtxtBuscar;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtObservacion;
    private javax.swing.JTextField jtxtPrecio;
    private javax.swing.JTextField jtxtRuta;
    // End of variables declaration//GEN-END:variables

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) {
            objDtm.removeRow(0);
        }
    }

    private void habilitarControles(boolean b) {
        jtxtNombre.setEditable(b);
        jtxtPrecio.setEditable(b);
        jtxtObservacion.setEditable(b);

        jbtnGrabar.setEnabled(b);
        jbtnCancelar.setEnabled(b);
        jbtnNuevo.setEnabled(!b);
        jbtnEditar.setEnabled(!b);
        jbtnBorrar.setEnabled(!b);
        jbtnSalir.setEnabled(!b);

        jtxtBuscar.setEditable(!b);
        jtxtNombre.grabFocus();
    }

    private void limpiarControles() {
        jtxtCodigo.setText("");
        jtxtNombre.setText("");
        jtxtPrecio.setText("");
        jtxtObservacion.setText("");
        jtxtBuscar.setText("");
        jtxtRuta.setText("");
        jlblFoto.setIcon(null);
        limpiarJTable();
    }

    public void reproducirSonido(String nombre) {
        try {
            String ruta = "src/sonidos/" + nombre + ".wav"; // Carpeta donde guardas tus audios
            File archivo = new File(ruta);
            if (!archivo.exists()) {
                System.err.println("No se encontró el archivo: " + ruta);
                return;
            }
            AudioInputStream audio = AudioSystem.getAudioInputStream(archivo);
            Clip clip = AudioSystem.getClip();
            clip.open(audio);
            clip.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
